#!/usr/bin/env nextflow

// Include modules
include { sayHello          }       from './modules/sayHello.nf'
include { convertToUpper    }       from './modules/convertToUpper.nf'
include { collectGreetings  }       from './modules/collectGreetings.nf'
include { cowpy             }       from './modules/cowpy.nf'
include { copy_file         }       from './modules/copy_file.nf'

/*
 * Pipeline parameters
 */
params {
    input: Path
    batch: String
    character: String
}

workflow {

    main:
    // create a channel for inputs from a CSV file
    greeting_ch = channel.fromPath(params.input)
                        .splitCsv()
                        .map { line -> line[0] }
    // emit a greeting
    sayHello(greeting_ch)
    // convert the greeting to uppercase
    convertToUpper(sayHello.out)
    // collect all the greetings into one file
    collectGreetings(convertToUpper.out.collect(), params.batch)
    // generate ASCII art of the greetings with cowpy
    cowpy(collectGreetings.out.outfile, params.character)
    // copy the file generated by cowpy
    copy_file(cowpy.out)

    publish:
    first_output = sayHello.out
    uppercased = convertToUpper.out
    collected = collectGreetings.out.outfile
    batch_report = collectGreetings.out.report
    cowpy_art = cowpy.out
    copied_file = copy_file.out
}

output {
    first_output {
        path { sayHello.name }
    }
    uppercased {
        path { convertToUpper.name }
    }
    collected {
        path { collectGreetings.name }
    }
    batch_report {
        path { collectGreetings.name }
    }
    cowpy_art {
        path { cowpy.name }
    }
    copied_file {
        path { copy_file.name }
    }
}
